USE [master]
GO

/****** Object:  Database [È¤¶©»õ]    Script Date: 07/05/2013 00:04:59 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'È¤¶©»õ')
DROP DATABASE [È¤¶©»õ]
GO

USE [master]
GO

/****** Object:  Database [È¤¶©»õ]    Script Date: 07/05/2013 00:04:59 ******/
CREATE DATABASE [È¤¶©»õ] ON  PRIMARY 
( NAME = N'È¤¶©»õ', FILENAME = N'D:\Êý¾Ý¿âÎÄ¼þ\È¤¶©»õ\È¤¶©»õ.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'È¤¶©»õ_log', FILENAME = N'D:\Êý¾Ý¿âÎÄ¼þ\È¤¶©»õ\È¤¶©»õ_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB )
GO

--ALTER DATABASE [È¤¶©»õ] SET COMPATIBILITY_LEVEL = 100
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [È¤¶©»õ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [È¤¶©»õ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET ARITHABORT OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [È¤¶©»õ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [È¤¶©»õ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [È¤¶©»õ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [È¤¶©»õ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

--ALTER DATABASE [È¤¶©»õ] SET TRUSTWORTHY OFF 
--GO

ALTER DATABASE [È¤¶©»õ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [È¤¶©»õ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [È¤¶©»õ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

--ALTER DATABASE [È¤¶©»õ] SET HONOR_BROKER_PRIORITY OFF 
--GO

ALTER DATABASE [È¤¶©»õ] SET  READ_WRITE 
GO

ALTER DATABASE [È¤¶©»õ] SET RECOVERY FULL 
GO

ALTER DATABASE [È¤¶©»õ] SET  MULTI_USER 
GO

ALTER DATABASE [È¤¶©»õ] SET PAGE_VERIFY CHECKSUM  
GO

--ALTER DATABASE [È¤¶©»õ] SET DB_CHAINING OFF 
--GO


